# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - MewahProcurement

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Set up environment variables
        run: |
          echo "OPENAI_DEPLOYMENT_NAME=$(echo '${{ secrets.AZURE_SECRET }}' | awk -F ';' '{for(i=1;i<=NF;i++){split($i,a,"="); if(a[1]=="OPENAI_DEPLOYMENT_NAME") print a[2]}}')" >> $GITHUB_ENV
          echo "AZURE_OPENAI_ENDPOINT=$(echo '${{ secrets.AZURE_SECRET }}' | awk -F ';' '{for(i=1;i<=NF;i++){split($i,a,"="); if(a[1]=="AZURE_OPENAI_ENDPOINT") print a[2]}}')" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=$(echo '${{ secrets.AZURE_SECRET }}' | awk -F ';' '{for(i=1;i<=NF;i++){split($i,a,"="); if(a[1]=="OPENAI_API_KEY") print a[2]}}')" >> $GITHUB_ENV
          echo "AZURE_SECRET=$(echo '${{ secrets.AZURE_SECRET }}' | awk -F ';' '{for(i=1;i<=NF;i++){split($i,a,"="); if(a[1]=="OPENAI_API_KEY") print a[2]}}')" >> $GITHUB_ENV
          

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E9D9179C42DF46A3832AEFA7BBDFCEF0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CB9C7B95AC9841B79D2ACBACA84B85C3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F6FDFBCCC3984E68B48FB2C74736260D }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'MewahProcurement'
          slot-name: 'Production'
